version: 3.9

services:
  redis:
    container_name: 'redis_platon_core_backend'
    image: redis:7.0.4-alpine3.16
    command: redis-server
    ports:
      - "16379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
