version: '3.9'

services:
  redis:
    container_name: 'redis_medium_lite'
    image: redis:7.0.4-alpine3.16
    command: redis-server
    ports:
      - "16379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
